Add a delegateCall test regarding memory
morpho-labs/morpho-utils pull request #25
Opened 2022-07-29 12:01 UTC by AtomicAzzaz

This test asserts that the delegateCall function of the delegateCall library leaves the memory in the same state as a the targetDelegateCallBehaviour function - which was the first implementation of the delegateCall library before being optimized in yul. This test compares the free memory pointer value and the full memory state using both functions. 

The idea behind targetDelegateCallBehaviourAndReturnMemoryAndPointer is to write in the memory before and after the delegateCall to not be in a trivial state with only 0's in memory. We test the memory on various data types returned by the delegateCall. 

Note: it is possible to make a full working implementation having this test failing (like having the free mem pointer further than ref implem) but is I believe not safe to do.

2022-08-01 07:24 UTC, Rubilmax approved these changes
useful!
Could we extract `targetDelegateCallBehaviour` to a DelegateCallRef contract?
To keep the same architecture as for the other utils

2022-08-04 17:21 UTC, MerlinEgalite requested changes
Small changes to apply but overall LGTM

2022-08-04 17:21 UTC, MerlinEgalite commented on test/TestDelegateCall.sol
> +            //We write a slot in the memory before the call
```suggestion
            // We write a slot in the memory before the call.
```

2022-08-04 17:21 UTC, MerlinEgalite commented on test/TestDelegateCall.sol
> +            //We write a slot in the memory after the call
```suggestion
            // We write a slot in the memory after the call.
```

2022-08-04 17:21 UTC, MerlinEgalite commented on test/TestDelegateCall.sol
> +        //We store the memory in allMem
```suggestion
        // We store the memory in allMem.
```

2022-08-04 17:21 UTC, MerlinEgalite commented on test/TestDelegateCall.sol
> +        //as a targetBehaviour function corresponding to the desired behavior.
```suggestion
        // This test makes sure that the delegateCall function of our library acts on the memory in the exact same way 
        // as a targetBehaviour function corresponding to the desired behavior.
```

2022-08-08 09:22 UTC, MerlinEgalite approved these changes

2022-08-08 09:22 UTC, merged