Optimized min&max functions
morpho-labs/morpho-utils pull request #30
Opened 2022-07-31 10:34 UTC by AtomicAzzaz

Before:
![image](https://user-images.githubusercontent.com/75758585/182022141-80637f11-70cb-4921-8840-4afdcbc06c3d.png)
After:
![image](https://user-images.githubusercontent.com/75758585/182022076-7b6c0a68-24d7-47e9-ad9a-83697ffb4142.png)

2022-07-31 10:41 UTC, MathisGD requested changes
Smart and aesthetic !
Just one change requested

2022-07-31 10:41 UTC, MathisGD commented on src/math/Math.sol
> +            z := add(mul(x, lt(x,y)),mul(y, iszero(lt(x,y))))
It seems that there has been no automatic formatting here

2022-07-31 15:27 UTC, MathisGD approved these changes

2022-07-31 16:53 UTC, makcandrov commented
The same strat can be applied to `zeroFloorSub`:

```solidity
function zeroFloorSub(uint256 x, uint256 y) internal pure returns (uint256 z) {
          assembly {
              z := mul(gt(x, y), sub(x, y))
          }
}
```

from 399 to 361 gas

2022-07-31 17:13 UTC, AtomicAzzaz commented
> The same strat can be applied to `zeroFloorSub`:
> 
> ```solidity
> function zeroFloorSub(uint256 x, uint256 y) internal pure returns (uint256 z) {
>           assembly {
>               z := mul(gt(x, y), sub(x, y))
>           }
> }
> ```
> 
> from 399 to 361 gas

Of course!

2022-07-31 17:26 UTC, MathisGD commented
> Of course!

@AtomicAzzaz you want to do it or should I do it ?

2022-07-31 17:27 UTC, AtomicAzzaz commented
> > Of course!
> 
> @AtomicAzzaz you want to do it or should I do it ?

I've already done it!

2022-07-31 17:28 UTC, MerlinEgalite approved these changes
LGTM

2022-07-31 17:30 UTC, MathisGD approved these changes

2022-07-31 17:31 UTC, merged

2022-08-01 07:06 UTC, QGarchery reviewed
Cool PR <3