Add wad ray math
morpho-labs/morpho-utils pull request #4
Opened 2022-07-15 17:28 UTC by MerlinEgalite

Gas comparisons:

1. Against Aave V3 lib
<img width="761" alt="Screenshot 2022-07-17 at 12 15 15" src="https://user-images.githubusercontent.com/44097430/179399624-7512d114-3e0d-426d-beb2-fcf83407bbc7.png">

2. Against the optimized version of the V2
<img width="759" alt="Screenshot 2022-07-17 at 12 15 31" src="https://user-images.githubusercontent.com/44097430/179399637-d3c32ba3-5662-4e08-8ed9-a118ee560875.png">

2022-07-18 08:39 UTC, Rubilmax approved these changes

2022-07-27 16:22 UTC, AtomicAzzaz approved these changes

2022-07-27 17:00 UTC, AtomicAzzaz requested changes
each saves 7 gas

2022-07-27 20:29 UTC, AtomicAzzaz approved these changes

2022-07-28 07:20 UTC, merged